apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/leonseng/terraform-everything.git
    targetRevision: HEAD
    path: eks-gitops/demo/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
